# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules:
  - identifier_name
  - todo
  - type_name
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
#  - discouraged_optional_boolean
#  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - explicit_self
  - fallthrough
  - fatal_error_message
  - file_name
  - file_name_no_space
#  - file_types_order
  - first_where
  - flatmap_over_map_reduce
#  - force_unwrapping
#  - implicit_return
#  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
#  - missing_docs
  - modifier_order
#  - multiline_arguments
#  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nslocalizedstring_key
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_subject
  - prohibited_super_call
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - sorted_first_last
  - static_operator
  - switch_case_on_newline
  - toggle_bool
#  - trailing_closure
#  - type_contents_order
  - typesafe_array_init
  - unneeded_parentheses_in_closure_argument
  - unavailable_function
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
#  - vertical_whitespace_opening_braces
  - yoda_condition

force_cast: warning
force_try: warning
line_length:
  warning: 120
  error: 240
  ignores_comments: true
function_body_length:
  warning: 60
type_body_length: [200, 400]

trailing_whitespace:
  ignores_empty_lines: true

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
