name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      # with:
        # The SDK to use for building.
        # sdk: iOS
